---
title: "`.gitignore`, тесты, github hooks"
author: "Г. Мороз, Н. Хауэлл"
date: "9 декабря 2021"
output: 
  html_document:
    toc: true
    toc_position: right
    toc_depth: 2
    toc_float: yes
    number_sections: true
---

```{r setup, include=FALSE}
library('knitr')
knit_hooks$set(prompt = function(before, options, envir) {options(prompt = "$ ")})
opts_chunk$set(comment = "", prompt = TRUE)
```

# Прошлые встречи

* 2021.11.08, [видео](https://youtu.be/oslfxrYjt_A)
* 2021.12.02, [видео](https://youtu.be/3ULre3nuIhU), [материалы](https://agricolamz.github.io/2021.12.02_intro_to_linux_lexd_github_makefiles/)

# Cимволы подстановки (wildcards) в `bash`

В `bash` как и во многих языках программирования есть символы подстановки. Хоть я приведу все примеры с функцией `ls`, но легко представить себе и более осмысленные задачи. У нас есть папка где есть много файлов:

```{bash}
ls multiple_files
```

Мы можем вывести все файлы содержащие двойку, добавив `*` -- любое количество символов:

```{bash}
ls multiple_files/*2*
```

Это же используют для поиска файлов с каким-либо определенным расширением:

```{bash}
ls multiple_files/*.csv
```

Кроме того звездочку можно использовать и без каких либо окружающих символов, тогда будут перечислены все файлы. Например, следующий команда удаляет все файлы в папке `multiple_files`.

```{bash, eval = FALSE}
rm multiple_files/*
```

Если известно точное количество символов, то можно использовать символ `?`, который обозначает один символ. Выведем только файлы с четырьмя символами в названии:

```{bash}
ls multiple_files/????.*
```

Как и раньше, искать можно по расшерению:

```{bash}
ls multiple_files/a_1.???
```

Кроме того можно задавать группы при помощи квадратных скобок:

```{bash}
ls multiple_files/[aouie]*
```

# `.gitignore`
Символы подстановки очень полезны при создании файла `.gitignore`. `.gitignore` --- это специальный скрытый файл[^hidden], в котором вы можете перечислить файлы, которые `git` должен игнорировать (см. [документацию](https://git-scm.com/docs/gitignore)). 

[^hidden]: Скрытые файлы или дериктории начинаются с точки и не высвечиваются по команде `ls` (но высвечиваются по команде `ls -a`). Скрытые файлы часто хронят конфигурационные файлы или какие данные, которые используют программы. Эта категория файлов создано, чтобы пользователь случайно не переписал или удалил какой-то из файлов. 

В [прошлый раз](https://agricolamz.github.io/2021.12.02_intro_to_linux_lexd_github_makefiles/) мы обсуждали, что при создании морфологического анализатора в формате `lexd` нам достаточно обмениваться файлами `.lexd` и соответствующим `Makefile`ом, а результирующие файлы вроде `.hfst` и `.hfstol` (мы об этих еще не говорили) хотелось бы случайно не закоммитить на GitHub. В связи с этим в вашем репозитории имеет смысл перечислить файлы, которые мы хотим, чтобы не были на GutHub:

```.gitignore
*.att
*.hfst
*.hfstol
```

Позже может так случится, что вы будете хранить в той же папке литературу и/или данные, которые нельзя выкладывать, их тоже можно будет добавить в `.gitignore`. Кроме того у GitHub есть ограничения на размер файла (вроде 100мб?..), если он увидит большие файлы, то он не даст их закоммитить, так что если они есть в вашем проекте, их тоже можно будет добавить в `.gitignore`.














